# This file composes the f1tenth ROS gym and outputs RVIZ to the host

services:
  sim:
    image: f1tenth_gym_ros
    container_name: f1tenth_gym_ros
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/sim_ws/src/f1tenth_gym_ros
    privileged: true
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]